### ISSUE TITLE
Multiple-objects page

### ISSUE THREAD

**Issue by typpo** [judymou/spacedb#14]
Comparison page that allows you to search for and add multiple objects to one 3d viz

**Comment by judymou** [comment]
made progress with commit c5d5fbbcec5224f09ba6ccf21d9aded92ffa9075

The next step is to style the page better and add a way for the to share

**Comment by typpo** [comment]
I just spent some time styling your new page!  Check it out c7b055b074d2b77894c014038902504c421665c2
